name: c4_harchuvannya
publish_to: 'none'
description: Cross-platform client for C4 food accounting and calculations.
version: 0.8.4+13

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: 9.2.4
  shared_preferences: 2.3.5
  share_plus: 10.1.4
  http: 1.2.2
  package_info_plus: 8.1.4
  url_launcher: 6.3.2
  archive: 3.6.1
  path_provider: 2.1.5
  open_filex: 4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/templates/report_template.docx
    - assets/data/report_people.json
